# https://school.programmers.co.kr/learn/courses/30/lessons/164668
SELECT
    U.USER_ID AS USER_ID, U.NICKNAME AS NICKNAME, B.TOTAL_SALES AS TOTAL_SALES
FROM
    USED_GOODS_USER AS U
INNER JOIN
    (SELECT
        WRITER_ID, SUM(IF(STATUS = 'DONE', PRICE, 0)) AS TOTAL_SALES
     FROM
        USED_GOODS_BOARD
     GROUP BY
        WRITER_ID
     HAVING
        TOTAL_SALES >= 700000) AS B
ON
    B.WRITER_ID = U.USER_ID
ORDER BY
    TOTAL_SALES ASC